### ISSUE TITLE
Is there a prebuilt VirtualBox image for v2?

### ISSUE THREAD

**Issue by fredericoschardong** [nemethf/escape#1]
Hi,

I read your paper and want to use ESCAPE in my research, however, there is no clear instructions about where to find the prebuilt VirtualBox image. I've found [this v1](http://sb.tmit.bme.hu/mediawiki/index.php/ESCAPEv1#Installation_instructions) link in your page but apparently this is not the latest version as [the page pointed in your paper](http://sb.tmit.bme.hu/mediawiki/index.php/ESCAPE#ESCAPE_at_a_glance) says v1 is an older version. Is there a prebuilt VirtualBox image for v2? If there is none then can you please create one?

Thanks!

**Comment by nemethf** [comment]
I think there are no prebuilt VMs available for v2, but at least the codebase is finally released. Take a look at here: https://github.com/hsnlab/escape
